// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Primeira.Models;
using System;

namespace Primeira.Migrations
{
    [DbContext(typeof(LabComrpasBdContext))]
    partial class LabComrpasBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Primeira.Models.Despesa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria")
                        .IsRequired();

                    b.Property<string>("NomeDespesa")
                        .IsRequired();

                    b.Property<bool>("Pago");

                    b.Property<int>("Quantidade");

                    b.Property<double>("Valor");

                    b.HasKey("ID");

                    b.ToTable("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
